### ISSUE TITLE
Client error response: {"errors":[{"message":"Not Found Space.","code":6,"moreInfo":""}]}

### ISSUE THREAD

**Issue by kurosukee** [itigoppo/backlog#4]
# 事象
API KEYによる認証後、「認証ユーザー情報の取得」を実行した際にエラーが発生しました。
※エラーの詳細は下記参照。

■エラーが発生した処理

```
$backlog->users->myself();
```

■エラーの内容
```
Client error: `GET https://{SPACE NAME}.backlog.jp/api/v2/users/myself?apiKey={API KEY}` resulted in a `404 Not Found` response: {"errors":[{"message":"Not Found Space.","code":6,"moreInfo":""}]}
```

# 実行環境
PHP 7.2.16
Laravel Framework 5.5

# 原因
ホスト名のルートドメインが「jp」になっている
https://{SPACE NAME}.backlog.jp/api/v2/users/myself?apiKey={API KEY}

# 対応策
ホスト名のルートドメインを「com」に変更する
https://github.com/itigoppo/backlog-api/blob/master/src/Connector/Connector.php#L7

**Comment by itigoppo** [comment]
うーーーん？
https://developer.nulab.com/ja/docs/backlog/auth/
.jpのままだから全体が変わったわけじゃないのかな、、、。

@kurosukee 
もしかして.comスペースでしょうか？

**Comment by itigoppo** [comment]
https://backlog.com/ja/blog/backlog-jp-change-domain-backlog-com/#important-announcement-for-backlog-developer

これかー。
全部がまだ切り替わってないから判断できるようにしないとなのかー。なるほど。かんがえます！

**Comment by biplobice** [comment]
@itigoppo & @kurosukee 
Everything isn't switched yet. I'm still able to access with `.jp`

**Comment by itigoppo** [comment]
@kurosukee 

@soudai さんにより修正PRきたので適応して1.2.0でリリースしました。
